<?php 
    session_start();
    ob_start();

    //SET ACTIVE PAGE
    $_SESSION["active_page"]="list";
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>Sanovi Q-Generator User Guide</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
    <?php 
            include "../../includes/config.php";
            include "../../includes/php_functions.php";
        
            change_session_id();
            check_session_expiry();
        ?>
            <?php
            if($_SESSION["authentication"] == "passed"){ 
                
        ?>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Sanovi Q-Generator User Guide</h1>
                <p style="align:justify">Q Generator is an advance Quote generator of Sanovi DRM Software Product Sale. A series of questions asked by the field engineers / pre sales guys to customers and the DRM quote is generated and sent to Customers for acceptance.
                    <br><br>This document is the complete user guide for Q-Generator Application</p>
                <h4><strong>LOGIN : </strong></h4>
                <ul>
                    <li>Open any Internet Browser and type the url <a href="http://quote.sanovi.com" target="_blank">http://quote.sanovi.com</a></li>
                    <li>Enter your login credentials shared by your admin and click on Login Button to login</li>
                    <li>Maximum of five login attempts are permitted. User Name will be blocked after fifth attempt.
                        <br>Contact your admin to reset the login</li>
                    <li>Click on Forget Password option to reset password on your own. This sends a password reset link to registered email id to reset password</li>
                    <li>Password Policy : Minimum 8 Characters. A-Z, a-z, 0-9 characters are permitted</li>
                </ul>
                <br>
                <img class="img-responsive" src="images/Login-Page.jpg" alt="sanovi Q-Generator login-page">
                <br>
                <h4><strong>QUOTE LIST</strong></h4>
                <ul>
                    <li>After Successful login, you will be redirected to Quote List</li>
                    <li>Select any option from “Select the View” to see the quotes. Following Options will be provided</li>
                </ul>
                <ul class="list">
                      <li><strong>Recent Quotes – </strong>Displays 5 recent quotes you have generated</li>
                      <li><strong>My Quotes – </strong>Displays all the quotes generated by you</li>
                      <?php if($_SESSION["userrole"]!="Quote Requestor"){ ?>
                          <?php if($_SESSION["userrole"]=="Administrator" || $_SESSION["userrole"]=="Chief Executive Officer" || $_SESSION["userrole"]=="Chief Financial Officer"){ ?>
                                <li><strong>All Quotes – </strong>Displays complete collection of quotes generated by Sanovi Team</li>
                          <?php } ?>
                          <li><strong>Quotes for Approval – </strong>Displays the quotes generated by your team and waiting for your approval</li>
                          <li><strong>Approved Quotes – </strong>Displays quotes approved by you</li>
                      <?php } ?>
                    
                </ul>
                <br>
                <img class="img-responsive" src="images/Dashboard-Sanovi-Q-Generator.jpg" alt="Dash-board---Sanovi-Q-Generator">
                <br>
                <?php if($_SESSION["userrole"]=="Administrator" || $_SESSION["userrole"]=="Chief Executive Officer" || $_SESSION["userrole"]=="Chief Financial Officer"){ ?>
                    <img class="img-responsive" src="images/Dashboard-With-Options.jpg" alt="Dashboard-With-Options">
                <?php } ?>
                <h4><strong>PROFILE</strong></h4>
                <ul>
                    <li><strong>My Profile – </strong>Displays your profile</li>
                    <li><strong>Change Password – </strong>Select the option “Change Password” in the left side menu of Profile page </li>
                </ul>
                
                <?php if($_SESSION["userrole"]=="Administrator"){ ?>
                <br>
                <img class="img-responsive" src="images/Profile.jpg" alt="Profile">
                <br>
                <h4><strong>ADMIN</strong></h4>
                <ul>
                    <li><strong>User List – </strong>Displays list of users added. You can edit/reset password/delete user using one touch buttons</li>
                    <li><strong>Add User – </strong>Creates a new user profile</li>
                    <li><strong>Delete User – </strong>Deletes an user profile</li>
                    <li><strong>Modify User – </strong>Modify the user profile</li>
                    <li><strong>Reset Password – </strong>Reset / Unblock user login credentials</li>
                    <li><strong>Modify Table Values – </strong>Modify Table Values of Quote Generator Database</li>
                    <li><strong>Change Password – </strong>Select the option “Change Password” in the left side menu of Profile page </li>
                </ul>
                <br>
                <img class="img-responsive" src="images/Sanovi-Q-Generator-admin-user-list.jpg" alt="Sanovi-Q-Generator-admin-user-list">
                <?php } ?>
                
                <br>
                <h4><strong>QUOTE GENERATOR</strong></h4>
                <ul>
                    <li>Select the option “Quote Generator” from main menu to generate Quote</li>
                    <li>Quote Generation is split into four sections</li>
                </ul>
                <ul class="list">
                    <li><strong>Quote Request – </strong>Enter Customer Requirement Data</li>
                </ul>
                <ol class="number-list">
                    <li>Select Product, License Type, Country, Currency, Mode of Sale & Product Module from respective drop down list boxes. Enter Opportunity Name, Customer Name & Partner in the textboxes(Only Alpha Numeric values accepted). Click Next button.</li></ol>
                    <br>
                    <img class="img-responsive" src="images/Sanovi-Q-Generator-first-section1.jpg" alt="Sanovi-Q-Generator-first-section">
                    <br>
                    <img class="img-responsive" src="images/Sanovi-Q-Generator-second-section-1.jpg" alt="Sanovi-Q-Generator-first-section-1">
                    <br>
                <ol start="2" class="number-list">
                    <li>Enter 2-Site License Configuration quantities & 3-Site License Configuration and click Next Button. Only Numeric values accepted. Advanced replicator panels will display appropriate Advanced Replicators upon entering VM Image Servers and Bare Metal Servers. Click on More Button to enter more Servers and Databases. Click Next button</li>
                    <li>Enter Product Support Years required. Maximum - 7 years and Minimum – 1 year. Select Professional Service Requirement including 3 Site/bunker Site Configuration to customize the requirement</li></ol>
                    <ul class="list" style="margin-left:55px;">
                        <li><strong>Default - </strong>Scope of Service = Full & Type of Service = Onsite</li>
                        <li><strong>Customizing – </strong>Select Partial from Scope of Service to enter quantity of implementation services required for 2 Site & 3 Site license quantities. Max quantity allowed will be depend upon the respective 2 Site & 3 Site license quantity entered</li>
                    </ul>
                
                    <br>
                    <img class="img-responsive" src="images/Sanovi-Q-Generator-third-section-1.jpg" alt="Sanovi-Q-Generator-third-section-1">
                    <br>
                    <img class="img-responsive" src="images/Sanovi-Q-Generator-third-section-2.jpg" alt="Sanovi-Q-Generator-third-section-1">
                    <br>
                <ol start="4" class="number-list">
                    <li>Click Next Button to Review Customer Requirement Data</li>
                </ol>
               <ul class="list" style="margin-left:0px;">
                   <li><strong>Config Review – </strong>Review the entered Customer Requirement Data. This is the page where you can review the final configuration of customer. Upon Clicking Next Button, you can no longer come back for further reviewing</li>
                   <img class="img-responsive" src="images/Sanovi-Q-Generator-review-configuration.jpg" alt="Sanovi-Q-Generator-review-configuration">
                    <br>
                    <li><strong>Review & Discounts – </strong>Enter Discounts and Review the quote</li>
                </ul>
               <ol class="number-list">
                    <li>Maximum discounts allowed to enter will be based on role</li>
                    <li>Quote can be finalized only if entered discount value is lesser than maximum discount</li>
                   <img class="img-responsive" src="images/Sanovi-Q-Generator---quote.jpg" alt="Sanovi-Q-Generator---quote">
                    <br>
                    <li>Quote will be sent to reporting manager for approval if entered discount value exceeds maximum allowed discount
                    </li>
                   <img class="img-responsive" src="images/Sanovi-Q-Generator---approver-alert-.jpg" alt="Sanovi-Q-Generator---approver-alert">
                    <br>
                </ol>
                <ul class="list" style="margin-left:0px;">
                    <li><strong>Quote Finalize – </strong>Confirmation screen after the quote is finalized</li>
                </ul>
                <ol class="number-list">
                    <li>You can enter an email id to email the quote / Download or preview the quote</li>
                </ol>
                <img class="img-responsive" src="images/Sanovi-Q-Generator---finalized-quote.jpg" alt="Sanovi-Q-Generator---finalized-quote">
                    <br>
                <br>
                <br>
                <br>
                <br>
                <span><center>For more info please contact your Admin</center></span>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
    <?php 
            include "../../includes/footer.php"; 
            }else {
                header('location:../index.php');
            }
            ob_flush()
        ?>
</body>

</html>