<title> Sanovi Q-Generator </title>
<meta charset="UTF-8">
<link rel="shortcut icon" href="../favicon.ico" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="../css/style.css">
<link rel="stylesheet" href="../css/style-bg-other-pages.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="../js/menu.js"></script>

<?php
    session_start(); 
    ob_start();
    # Include the Autoloader (see "Libraries" for install instructions)
    require 'vendor/autoload.php';
    use Mailgun\Mailgun;

    # Instantiate the client.
    $mgClient = new Mailgun('key-d1ed1feffaa3daf3750d037e38a2e65c');
    $domain = "pyraminds.in";
    if($_SESSION["authentication"] == "passed"){
        include "../../includes/header-plain.php";
        include "../../includes/mainmenu-mobile.php";
        include "../../includes/mainmenu.php";
        
        $emailaddress=$_GET["emailid"];
        $refId=$_GET["refId"];
        $verId=$_GET["verId"];
        
        $approver_name=$_GET["appname"];
        
		$quote_requestor_emailid=$_SESSION["emailid"];
        $subject='Approval Alert for Quote '.$refId.' - '.$verId;
        
        # Make the call to the client.
        $result = $mgClient->sendMessage($domain, array(
            'from'    => 'Sanovi Technologies Pvt Ltd<quote@sanovi.com>',
            'to'      => $emailaddress,
			'cc'      => $quote_requestor_emailid,
            'subject' => $subject,
            'html'    => '<html>Hello '.$approver_name.',<br><br>A Quote with Reference No. <b>'.$refId.'</b> and Version No. <b>'.$verId.'</b> is Generated. Please login to Q-Generator Dashboard for more details.<br><br>--<br><i>THIS IS AN AUTOMATED MAIL GENERATED BY Q-GENERATOR APPLICATION.</i></html>'
        ));
		session_regenerate_id(true);
        header('location: ../quote-saved.php?emailid='.$emailaddress.'&refId='.$refId.'&$verId='.$verId.'&appname='.$approver_name);
		die();
        ob_flush();
    }
?>